version: '3'

services:
  nosql-db:
    restart: always
    image: mongo:6.0
    container_name: ${MONGO_DB_NAME}
    command: ['--auth']
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./db-data:/data/db

volumes:
  db-data:
    external: false